# Generated by Django 4.0.3 on 2022-03-17 12:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('type', models.CharField(choices=[('seasonal', 'Seasonal'), ('single', 'Single')], max_length=10)),
                ('category', models.CharField(choices=[('Originals', 'Originals'), ('Horror', 'Horror'), ('Action', 'Action'), ('Romance', 'Romance'), ('Documentary', 'Documentary'), ('Comedy', 'Comedy'), ('Sci-fi', 'Sci-fi'), ('Drama', 'Drama'), ('Fantasy', 'Fantasy'), ('Crime', 'Crime'), ('Thriller', 'Thriller')], max_length=20)),
                ('videos', models.CharField(max_length=225)),
                ('image', models.CharField(max_length=225)),
                ('flyer', models.CharField(max_length=225)),
                ('age_limit', models.CharField(choices=[('All', 'All'), ('Kids', 'Kids')], max_length=10)),
                ('premiere', models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], default='NO', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='action',
        ),
        migrations.DeleteModel(
            name='documentary',
        ),
        migrations.DeleteModel(
            name='filmedmovie',
        ),
        migrations.DeleteModel(
            name='horror',
        ),
        migrations.DeleteModel(
            name='netflixorginals',
        ),
        migrations.DeleteModel(
            name='romance',
        ),
    ]
