# Generated by Django 4.0.3 on 2022-03-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_movie_delete_action_delete_documentary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('Trending', 'Trending'), ('Popular', 'Popular'), ('New Release', 'New Release'), ('Most Watched', 'Most Watched')], default='Popular', max_length=20),
        ),
    ]
