# Generated by Django 4.1.7 on 2023-02-17 05:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('type', models.CharField(choices=[('seasonal', 'Seasonal'), ('single', 'Single')], max_length=10)),
                ('category', models.CharField(choices=[('Originals', 'Originals'), ('Horror', 'Horror'), ('Action', 'Action'), ('Romance', 'Romance'), ('Documentary', 'Documentary'), ('Comedy', 'Comedy'), ('Sci-fi', 'Sci-fi'), ('Drama', 'Drama'), ('Fantasy', 'Fantasy'), ('Crime', 'Crime'), ('Thriller', 'Thriller')], max_length=20)),
                ('videos', models.CharField(max_length=225)),
                ('image', models.CharField(max_length=225)),
                ('flyer', models.CharField(max_length=225)),
                ('age_limit', models.CharField(choices=[('All', 'All'), ('Kids', 'Kids')], max_length=10)),
                ('status', models.CharField(choices=[('Trending', 'Trending'), ('Popular', 'Popular'), ('New Release', 'New Release'), ('Most Watched', 'Most Watched')], max_length=20)),
                ('premiere', models.CharField(choices=[('NO', 'NO'), ('YES', 'YES')], default='NO', max_length=10)),
            ],
        ),
    ]
