# Generated by Django 4.1.7 on 2023-02-17 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playbacks', '0002_useraccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
