export const MOVIE_LIST_REQUEST = 'MOVIE_LIST_REQUEST'
export const MOVIE_LIST_SUCCESS = 'MOVIE_LIST_SUCCESS'
export const MOVIE_LIST_FAIL = 'MOVIE_LIST_FAIL'

export const PREMIERE_MOVIE_REQUEST = 'PREMIERE_MOVIE_REQUEST'
export const PREMIERE_MOVIE_SUCCESS = 'PREMIERE_MOVIE_SUCCESS'
export const PREMIERE_MOVIE_FAIL = 'PREMIERE_MOVIE_FAIL'

export const NETFLIX_ORIGINALS_REQUEST = 'NETFLIX_ORIGINALS_REQUEST'
export const NETFLIX_ORIGINALS_SUCCESS = 'NETFLIX_ORIGINALS_SUCCESS'
export const NETFLIX_ORIGINALS_FAIL = 'NETFLIX_ORIGINALS_FAIL'

export const HORROR_MOVIES_REQUEST = 'HORROR_MOVIES_REQUEST'
export const HORROR_MOVIES_SUCCESS = 'HORROR_MOVIES_SUCCESS'
export const HORROR_MOVIES_FAIL = 'HORROR_MOVIES_FAIL'

export const ACTION_MOVIES_REQUEST = 'ACTION_MOVIES_REQUEST'
export const ACTION_MOVIES_SUCCESS = 'ACTION_MOVIES_SUCCESS'
export const ACTION_MOVIES_FAIL = 'ACTION_MOVIES_FAIL'

export const ROMANTIC_MOVIES_REQUEST = 'ROMANTIC_MOVIES_REQUEST'
export const ROMANTIC_MOVIES_SUCCESS = 'ROMANTIC_MOVIES_SUCCESS'
export const ROMANTIC_MOVIES_FAIL = 'ROMANTIC_MOVIES_FAIL'

export const DOCUMENTARY_MOVIES_REQUEST = 'DOCUMENTARY_MOVIES_REQUEST'
export const DOCUMENTARY_MOVIES_SUCCESS = 'DOCUMENTARY_MOVIES_SUCCESS'
export const DOCUMENTARY_MOVIES_FAIL = 'DOCUMENTARY_MOVIES_FAIL'





export const TRENDING_MOVIES_REQUEST = 'TRENDING_MOVIES_REQUEST'
export const TRENDING_MOVIES_SUCCESS = 'TRENDING_MOVIES_SUCCESS'
export const TRENDING_MOVIES_FAIL = 'TRENDING_MOVIES_FAIL'

export const POPULAR_MOVIES_REQUEST = 'POPULAR_MOVIES_REQUEST'
export const POPULAR_MOVIES_SUCCESS = 'POPULAR_MOVIES_SUCCESS'
export const POPULAR_MOVIES_FAIL = 'POPULAR_MOVIES_FAIL'

export const NEW_RELEASE_MOVIES_REQUEST = 'NEW_RELEASE_MOVIES_REQUEST'
export const NEW_RELEASE_MOVIES_SUCCESS = 'NEW_RELEASE_MOVIES_SUCCESS'
export const NEW_RELEASE_MOVIES_FAIL = 'NEW_RELEASE_MOVIES_FAIL'

export const MOST_WATCHED_MOVIES_REQUEST = 'MOST_WATCHED_MOVIES_REQUEST'
export const MOST_WATCHED_MOVIES_SUCCESS = 'MOST_WATCHED_MOVIES_SUCCESS'
export const MOST_WATCHED_MOVIES_FAIL = 'MOST_WATCHED_MOVIES_FAIL'