export const MOVIE_LIST_REQUEST = 'MOVIE_LIST_REQUEST'
export const MOVIE_LIST_SUCCESS = 'MOVIE_LIST_SUCCESS'
export const MOVIE_LIST_FAIL = 'MOVIE_LIST_FAIL'

export const NETFLIX_ORIGINALS_REQUEST = 'NETFLIX_ORIGINALS_REQUEST'
export const NETFLIX_ORIGINALS_SUCCESS = 'NETFLIX_ORIGINALS_SUCCESS'
export const NETFLIX_ORIGINALS_FAIL = 'NETFLIX_ORIGINALS_FAIL'